/* 
 * Automatically generated by socgen. DO NOT EDIT!
 * 
 * Copyright (c) 2015 Apple Inc. All rights reserved.
 * 
 * This document is the property of Apple Inc.
 * It is considered confidential and proprietary.
 * 
 * This document may not be reproduced or transmitted in any form
 * in whole or in part, without the express written permission of
 * Apple inc.
 */

#ifndef SPDS_S8000_B0_TUNABLE_AUST_SHM_CFG_H
#define SPDS_S8000_B0_TUNABLE_AUST_SHM_CFG_H

#define PCIE_APCIE_PHY_AUST0_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST0_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST0_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST0_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST0_SHM_CFG_DEFAULT_TUNABLES_S8000_B0 \
/* Key = default_tunable_key                                                      */ \
/* Register Macro Identifier       Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* AUST_SHM_CFG_BLK_CFG6_TXA */ 0x18,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{  /* AUST_SHM_CFG_BLK_CFG7_TXA */ 0x1c,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{                                  -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PHY_AUST1_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST1_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST1_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST1_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST1_SHM_CFG_DEFAULT_TUNABLES_S8000_B0 \
/* Key = default_tunable_key                                                      */ \
/* Register Macro Identifier       Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* AUST_SHM_CFG_BLK_CFG6_TXA */ 0x18,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{  /* AUST_SHM_CFG_BLK_CFG7_TXA */ 0x1c,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{                                  -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PHY_AUST2_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST2_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST2_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST2_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST2_SHM_CFG_DEFAULT_TUNABLES_S8000_B0 \
/* Key = default_tunable_key                                                      */ \
/* Register Macro Identifier       Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* AUST_SHM_CFG_BLK_CFG6_TXA */ 0x18,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{  /* AUST_SHM_CFG_BLK_CFG7_TXA */ 0x1c,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{                                  -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PHY_AUST3_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST3_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST3_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST3_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST3_SHM_CFG_DEFAULT_TUNABLES_S8000_B0 \
/* Key = default_tunable_key                                                      */ \
/* Register Macro Identifier       Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* AUST_SHM_CFG_BLK_CFG6_TXA */ 0x18,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{  /* AUST_SHM_CFG_BLK_CFG7_TXA */ 0x1c,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{                                  -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PHY_AUST4_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST4_SHM_CFG_BLK_CFG6_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST4_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_UMASK_S8000_B0 (0x1800)
#define PCIE_APCIE_PHY_AUST4_SHM_CFG_BLK_CFG7_TXA_DEFAULT_TUNABLE_VALUE_S8000_B0 (0x1800)

#define PCIE_APCIE_PHY_AUST4_SHM_CFG_DEFAULT_TUNABLES_S8000_B0 \
/* Key = default_tunable_key                                                      */ \
/* Register Macro Identifier       Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* AUST_SHM_CFG_BLK_CFG6_TXA */ 0x18,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{  /* AUST_SHM_CFG_BLK_CFG7_TXA */ 0x1c,           sizeof(uint32_t), 0x1800,      0x1800        }, \
{                                  -1,             -1,               -1,          -1            }

#endif /* SPDS_S8000_B0_TUNABLE_AUST_SHM_CFG_H */