/* 
 * Automatically generated by socgen. DO NOT EDIT!
 * 
 * Copyright (c) 2015 Apple Inc. All rights reserved.
 * 
 * This document is the property of Apple Inc.
 * It is considered confidential and proprietary.
 * 
 * This document may not be reproduced or transmitted in any form
 * in whole or in part, without the express written permission of
 * Apple inc.
 */

#ifndef SPDS_T8010_A0_TUNABLE_APCIE_CONFIG_H
#define SPDS_T8010_A0_TUNABLE_APCIE_CONFIG_H

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_UMASK_T8010_A0    (0xff)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_VALUE_T8010_A0    (0x28)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_UMASK_T8010_A0 (0xff)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_VALUE_T8010_A0 (0x28)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0             (0xd)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0             (0x5)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0          (0x2)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0            (0x1)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0            (0x1)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0         (0x1)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0         (0x1)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_UMASK_T8010_A0         (0x7f7f)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_VALUE_T8010_A0         (0x0)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0          (0x3)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_UMASK_T8010_A0        (0x8073ffff)
#define PCIE_APCIE_PORT0_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_VALUE_T8010_A0        (0x403d09)

#define PCIE_APCIE_PORT0_APCIE_CONFIG_DEFAULT_TUNABLES_T8010_A0 \
/* Key = default_tunable_key                                                              */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0xd,         0x5           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{  /* APCIE_CONFIG_BLK_MCACHE_HINT */      0x138,          sizeof(uint32_t), 0x7f7f,      0x0           }, \
{  /* APCIE_CONFIG_BLK_L1_SUBCTRL */       0x13c,          sizeof(uint32_t), 0x3,         0x2           }, \
{  /* APCIE_CONFIG_BLK_AF_TMOT_CTRL */     0x140,          sizeof(uint32_t), 0x8073ffff,  0x403d09      }, \
{                                          -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PORT0_APCIE_CONFIG_SECURE_ROM_TUNABLES_T8010_A0 \
/* Key = secure_rom_tunable_key                                                           */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0x2,         0x2           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{                                          -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_UMASK_T8010_A0    (0xff)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_VALUE_T8010_A0    (0x28)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_UMASK_T8010_A0 (0xff)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_VALUE_T8010_A0 (0x28)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0             (0xd)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0             (0x5)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0          (0x2)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0            (0x1)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0            (0x1)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0         (0x1)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0         (0x1)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_UMASK_T8010_A0         (0x7f7f)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_VALUE_T8010_A0         (0x0)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0          (0x3)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_UMASK_T8010_A0        (0x8073ffff)
#define PCIE_APCIE_PORT1_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_VALUE_T8010_A0        (0x403d09)

#define PCIE_APCIE_PORT1_APCIE_CONFIG_DEFAULT_TUNABLES_T8010_A0 \
/* Key = default_tunable_key                                                              */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0xd,         0x5           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{  /* APCIE_CONFIG_BLK_MCACHE_HINT */      0x138,          sizeof(uint32_t), 0x7f7f,      0x0           }, \
{  /* APCIE_CONFIG_BLK_L1_SUBCTRL */       0x13c,          sizeof(uint32_t), 0x3,         0x2           }, \
{  /* APCIE_CONFIG_BLK_AF_TMOT_CTRL */     0x140,          sizeof(uint32_t), 0x8073ffff,  0x403d09      }, \
{                                          -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PORT1_APCIE_CONFIG_SECURE_ROM_TUNABLES_T8010_A0 \
/* Key = secure_rom_tunable_key                                                           */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0x2,         0x2           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{                                          -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_UMASK_T8010_A0    (0xff)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_VALUE_T8010_A0    (0x28)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_UMASK_T8010_A0 (0xff)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_VALUE_T8010_A0 (0x28)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0             (0xd)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0             (0x5)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0          (0x2)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0            (0x1)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0            (0x1)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0         (0x1)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0         (0x1)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_UMASK_T8010_A0         (0x7f7f)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_VALUE_T8010_A0         (0x0)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0          (0x3)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_UMASK_T8010_A0        (0x8073ffff)
#define PCIE_APCIE_PORT2_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_VALUE_T8010_A0        (0x403d09)

#define PCIE_APCIE_PORT2_APCIE_CONFIG_DEFAULT_TUNABLES_T8010_A0 \
/* Key = default_tunable_key                                                              */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0xd,         0x5           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{  /* APCIE_CONFIG_BLK_MCACHE_HINT */      0x138,          sizeof(uint32_t), 0x7f7f,      0x0           }, \
{  /* APCIE_CONFIG_BLK_L1_SUBCTRL */       0x13c,          sizeof(uint32_t), 0x3,         0x2           }, \
{  /* APCIE_CONFIG_BLK_AF_TMOT_CTRL */     0x140,          sizeof(uint32_t), 0x8073ffff,  0x403d09      }, \
{                                          -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PORT2_APCIE_CONFIG_SECURE_ROM_TUNABLES_T8010_A0 \
/* Key = secure_rom_tunable_key                                                           */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0x2,         0x2           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{                                          -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_UMASK_T8010_A0    (0xff)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_DEFAULT_TUNABLE_VALUE_T8010_A0    (0x28)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_UMASK_T8010_A0 (0xff)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_PMETOACK_TMOTLIM_SECURE_ROM_TUNABLE_VALUE_T8010_A0 (0x28)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0             (0xd)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_INBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0             (0x5)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0          (0x2)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_INBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0            (0x1)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_OUTBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0            (0x1)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_UMASK_T8010_A0         (0x1)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_OUTBCTRL_SECURE_ROM_TUNABLE_VALUE_T8010_A0         (0x1)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_UMASK_T8010_A0         (0x7f7f)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_MCACHE_HINT_DEFAULT_TUNABLE_VALUE_T8010_A0         (0x0)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_UMASK_T8010_A0          (0x3)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_L1_SUBCTRL_DEFAULT_TUNABLE_VALUE_T8010_A0          (0x2)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_UMASK_T8010_A0        (0x8073ffff)
#define PCIE_APCIE_PORT3_APCIE_CONFIG_BLK_AF_TMOT_CTRL_DEFAULT_TUNABLE_VALUE_T8010_A0        (0x403d09)

#define PCIE_APCIE_PORT3_APCIE_CONFIG_DEFAULT_TUNABLES_T8010_A0 \
/* Key = default_tunable_key                                                              */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0xd,         0x5           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{  /* APCIE_CONFIG_BLK_MCACHE_HINT */      0x138,          sizeof(uint32_t), 0x7f7f,      0x0           }, \
{  /* APCIE_CONFIG_BLK_L1_SUBCTRL */       0x13c,          sizeof(uint32_t), 0x3,         0x2           }, \
{  /* APCIE_CONFIG_BLK_AF_TMOT_CTRL */     0x140,          sizeof(uint32_t), 0x8073ffff,  0x403d09      }, \
{                                          -1,             -1,               -1,          -1            }

#define PCIE_APCIE_PORT3_APCIE_CONFIG_SECURE_ROM_TUNABLES_T8010_A0 \
/* Key = secure_rom_tunable_key                                                           */ \
/* Register Macro Identifier               Register Offset Register Size     Tunable Mask Tunable Value */ \
{  /* APCIE_CONFIG_BLK_PMETOACK_TMOTLIM */ 0x90,           sizeof(uint32_t), 0xff,        0x28          }, \
{  /* APCIE_CONFIG_BLK_INBCTRL */          0x130,          sizeof(uint32_t), 0x2,         0x2           }, \
{  /* APCIE_CONFIG_BLK_OUTBCTRL */         0x134,          sizeof(uint32_t), 0x1,         0x1           }, \
{                                          -1,             -1,               -1,          -1            }

#endif /* SPDS_T8010_A0_TUNABLE_APCIE_CONFIG_H */