
name: Build

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo bash ci_build.bash

      - name: Upload back
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: .
          